kind: pipeline
name: rocker/geospatial:3.5

steps:
- name: build 'n check
  image: rocker/geospatial:3.5
  commands:
  - R CMD build .
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - export _R_CHECK_CRAN_INCOMING_=FALSE 
  - export _R_CHECK_FORCE_SUGGESTS_=FALSE 
  - R CMD check $FILE --as-cran

---

kind: pipeline
name: rocker/geospatial:latest

steps:
- name: build 'n check
  image: rocker/geospatial:latest
  commands:
  - mkdir ~/.R 
  - echo 'CXX11FLAGS = -g -O2 -Wall -pedantic -fstack-protector-strong -D_FORTIFY_SOURCE=2' > ~/.R/Makevars
  - R CMD build .
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - export _R_CHECK_CRAN_INCOMING_=FALSE 
  - export _R_CHECK_FORCE_SUGGESTS_=FALSE 
  - R CMD check $FILE --as-cran

---

kind: pipeline
name: rocker/geospatial:devel

steps:
- name: build 'n check
  image: rocker/geospatial:devel
  commands:
  - mkdir ~/.R 
  - echo 'CXX11FLAGS = -g -O2 -Wall -pedantic -fstack-protector-strong -D_FORTIFY_SOURCE=2' > ~/.R/Makevars
  - R CMD build .
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - export _R_CHECK_CRAN_INCOMING_=FALSE 
  - export _R_CHECK_FORCE_SUGGESTS_=FALSE 
  - R CMD check $FILE --as-cran
