language: r
r:
  - release
  - devel

dist: bionic

cache:
  - packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libgeos-dev
      - libgdal-dev
      - devscripts
