language: r
r:
  - release
  - devel

dist: trusty

cache:
  - packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libgeos-dev
      - libgdal-dev
